version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/modern"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: UTC
    assignees:
      - nikise1
    labels:
      - dependencies
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
